=== eclipse-opensmartclide/smartclide/context/context-extraction/src/test/resources/monitoring-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.atb-bremen.de" >
  <xs:element name="config">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="indexes"/>
        <xs:element ref="datasources"/>
        <xs:element ref="interpreters"/>
        <xs:element ref="monitors"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="indexes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="index"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="index">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="location" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="monitors">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="monitor"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="monitor">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="datasource" use="required" type="xs:IDREF"/>
      <xs:attribute name="index" use="required" type="xs:IDREF"/>
      <xs:attribute name="interpreter" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="datasources">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="datasource"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="datasource">
    <xs:complexType>
      <xs:attribute name="class" use="required"/>
      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="monitor" use="required"/>
      <xs:attribute name="options" use="required"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
      <xs:attribute name="uri" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="interpreters">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="interpreter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="interpreter">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="configuration"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="configuration">
    <xs:complexType>
      <xs:attribute name="analyser" use="required"/>
      <xs:attribute name="parser" use="required"/>
      <xs:attribute name="type" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== eclipse-opensmartclide/smartclide/context/context-extraction/src/test/resources/monitoring-filepair-config.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns="http://www.atb-bremen.de"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.atb-bremen.de monitoring-config.xsd">

	<indexes>
		<index id="index-dummy" location="indexes/dummy"></index>
	</indexes>

	<datasources>
		<datasource id="datasource-dummy" type="file"
			monitor="FilePairSystemMonitor"
			uri="target/test-classes/filepairmonitor"
			options="extensionOne=1&amp;extensionTwo=2"
			class="FilePairSystemDataSource" />
	</datasources>

	<interpreters>
		<interpreter id="interpreter-dummy">
			<configuration type="*"
				parser="DummyFilePairParser"
				analyser="DummyFilePairAnalyser" />
		</interpreter>

	</interpreters>
	
	<monitors>
		<monitor id="monitor-dummy" datasource="datasource-dummy" interpreter="interpreter-dummy"
			index="index-dummy" />
	</monitors>
	
</config>

=== eclipse-opensmartclide/smartclide/context/context-extraction/src/test/resources/monitoring-config.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns="http://www.atb-bremen.de"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.atb-bremen.de monitoring-config.xsd">

	<indexes>
		<index id="index-desma" location="indexes/desma"></index>
	</indexes>

	<datasources>
		<datasource id="datasource-desma" type="file"
			monitor="FileSystemMonitor"
			uri="target/test-classes/filepairmonitor"
			options="hiddenfiles=true"
			class="FileSystemDataSource" />
	</datasources>

	<interpreters>
		<interpreter id="interpreter-desma">
			<configuration type="vlv"
				parser="de.atb.core.monitoring.parser.file.VlvParser"
				analyser="de.atb.core.monitoring.analyser.file.VlvAnalyser" />
			<configuration type="trf"
				parser="de.atb.core.monitoring.parser.file.TrfParser"
				analyser="de.atb.core.monitoring.analyser.file.TrfAnalyser" />
		</interpreter>
	</interpreters>
	
	<monitors>
		<monitor id="monitor-desma" datasource="datasource-desma" interpreter="interpreter-desma"
			index="index-desma" />
	</monitors>
	
</config>
